export default {
    title: 'GraphUrlPing',
    setTime:'Set Time',
    about:'About',
    chooselanguage:'Choose Language',
    currenttime:'Current request duration',
    timeinput:'Input request duration',
    sure:'Sure',
    inputone:'Enter URL 1',
    inputtwo:'Enter URL 2',
    enter:'Enter',
    ping:'PING',
    settings:'Settings',
    about:'About',
    status:'Status',
    return:'Return to chart',
    max:'MAX',
    min:'MIN',
    avg:'AVG',
    add:'Add',
    start:'Start',
    input:'Please Enter URL',
    ok:"OK",
    delete:'Delete',
    cancel:'Cancel',
    toast1:'Input URL is null!',
    switchlanguage: 'Switch Language',
    language:'Language',
    requestinterval: 'Request Interval',
    currentlanguage: 'current language',
    //About页面的英文显示
    developmentunit: 'Development Unit',
    hDDevteam: 'HDDevTeam',
    developer: 'Developer',
    members: 'Some 19&20 RN Group Members',
    versionupdatetime: 'Version Update Time',
    iftherearebugsduringuse: 'If there are bugs during use',
    pleasecontact: 'Please Contact',
};
