export default {
    title: 'GraphUrlPing',
    setTime:'시간 설정',
    about:'...에 대하 여',
    chooselanguage:'선택 언어',
    currenttime:'현재 요청 시간',
    timeinput:'입력 요청 시간',
    sure:'확정 하 다.',
    inputone:'인터넷 주소 입력 1',
    inputtwo:'인터넷 주소 입력 2',
    enter:'들어가다',
    ping:'PING',
    status:'상태.',
    return:'리 턴 차 트',
    max:'MAX',
    min:'MIN',
    avg:'AVG',
};