export default {
    // title: 'GraphUrlPing',
    // //About页面的中文显示
    // developmentunit: '开发单位',
    // hDDevteam: '河南大学网络中心实验室',
    // developer: '开发人员',
    // members: '19级、20级RN组部分人员',
    // versionupdatetime: '版本更新时间',
    // iftherearebugsduringuse: '使用过程中，如果出现bugs',
    // pleasecontact: '请联系',
    title:'Graph URL Ping',
    input:'请输入URL',
    delete:'删除',
    add:'添加',
    test:'测试中',
    nourladded:'尚未添加需要Ping的网址',
    urlempty:'输入网址不能为空',
    maxfiveurl:'一次最多ping5个网址',
    selectinputbox:'请先选择输入框',
    Over:"完成",
    reject_Test:"请仔细核验网址",
    home: '主页',
    about:'关于我们',
    setting: '设置',
    history:'历史',
    developmentunit: '开发单位',
    hDDevteam: '河南大学网络中心实验室',
    developer: '开发人员',
    members: '19级、20级RN组部分人员',
    versionupdatetime: '版本更新时间',
    iftherearebugsduringuse: '使用过程中，如果出现bugs',
    pleasecontact: '请联系',
    version:"版本号：1.0.0",
    Theme:"主题颜色",
    aboutDetails:"版本号: v1.0.0\n更新时间: 2021/11/24",
    DoublePress:"再按一次退出应用",
    quitAlert:"确定要离开吗?",
    cancel:"取消",
    confirm:"确定",
    copy:"复制",
    ok:"关闭",
    max_five_site:"最多测试五个站点",
    Copy_success:"复制成功"


};
